import { Asset } from './types';

export const POPULAR_ASSETS: Asset[] = [
  // Top Mega Cap & Tech Stocks
  { symbol: 'AAPL', name: 'Apple Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/apple.com' },
  { symbol: 'MSFT', name: 'Microsoft Corp.', type: 'stock', logoUrl: 'https://logo.clearbit.com/microsoft.com' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', type: 'stock', logoUrl: 'https://logo.clearbit.com/nvidia.com' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/amazon.com' },
  { symbol: 'TSLA', name: 'Tesla Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/tesla.com' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/abc.xyz' },
  { symbol: 'META', name: 'Meta Platforms Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/meta.com' },
  { symbol: 'NFLX', name: 'Netflix Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/netflix.com' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', type: 'stock', logoUrl: 'https://logo.clearbit.com/amd.com' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/broadcom.com' },
  { symbol: 'INTC', name: 'Intel Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/intel.com' },
  { symbol: 'CRM', name: 'Salesforce Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/salesforce.com' },
  { symbol: 'ADBE', name: 'Adobe Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/adobe.com' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/cisco.com' },
  { symbol: 'ORCL', name: 'Oracle Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/oracle.com' },
  { symbol: 'IBM', name: 'International Business Machines', type: 'stock', logoUrl: 'https://logo.clearbit.com/ibm.com' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/qualcomm.com' },
  { symbol: 'TXN', name: 'Texas Instruments', type: 'stock', logoUrl: 'https://logo.clearbit.com/ti.com' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/servicenow.com' },
  { symbol: 'INTU', name: 'Intuit Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/intuit.com' },
  
  // Top Financials & Payments
  { symbol: 'V', name: 'Visa Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/visa.com' },
  { symbol: 'MA', name: 'Mastercard Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/mastercard.com' },
  { symbol: 'JPM', name: 'JPMorgan Chase', type: 'stock', logoUrl: 'https://logo.clearbit.com/jpmorganchase.com' },
  { symbol: 'BAC', name: 'Bank of America', type: 'stock', logoUrl: 'https://logo.clearbit.com/bankofamerica.com' },
  { symbol: 'WFC', name: 'Wells Fargo', type: 'stock', logoUrl: 'https://logo.clearbit.com/wellsfargo.com' },
  { symbol: 'C', name: 'Citigroup Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/citigroup.com' },
  { symbol: 'GS', name: 'Goldman Sachs', type: 'stock', logoUrl: 'https://logo.clearbit.com/goldmansachs.com' },
  { symbol: 'MS', name: 'Morgan Stanley', type: 'stock', logoUrl: 'https://logo.clearbit.com/morganstanley.com' },
  { symbol: 'AXP', name: 'American Express', type: 'stock', logoUrl: 'https://logo.clearbit.com/americanexpress.com' },
  { symbol: 'PYPL', name: 'PayPal Holdings', type: 'stock', logoUrl: 'https://logo.clearbit.com/paypal.com' },
  { symbol: 'BLK', name: 'BlackRock Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/blackrock.com' },
  { symbol: 'SQ', name: 'Block Inc. (Square)', type: 'stock', logoUrl: 'https://logo.clearbit.com/block.xyz' },

  // Top Consumer & Retail
  { symbol: 'WMT', name: 'Walmart Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/walmart.com' },
  { symbol: 'TGT', name: 'Target Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/target.com' },
  { symbol: 'HD', name: 'Home Depot', type: 'stock', logoUrl: 'https://logo.clearbit.com/homedepot.com' },
  { symbol: 'LOW', name: 'Lowe\'s Companies', type: 'stock', logoUrl: 'https://logo.clearbit.com/lowes.com' },
  { symbol: 'COST', name: 'Costco Wholesale', type: 'stock', logoUrl: 'https://logo.clearbit.com/costco.com' },
  { symbol: 'NKE', name: 'NIKE Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/nike.com' },
  { symbol: 'MCD', name: 'McDonald\'s Corp.', type: 'stock', logoUrl: 'https://logo.clearbit.com/mcdonalds.com' },
  { symbol: 'SBUX', name: 'Starbucks Corp.', type: 'stock', logoUrl: 'https://logo.clearbit.com/starbucks.com' },
  { symbol: 'KO', name: 'Coca-Cola Co.', type: 'stock', logoUrl: 'https://logo.clearbit.com/coca-cola.com' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/pepsico.com' },
  { symbol: 'PG', name: 'Procter & Gamble', type: 'stock', logoUrl: 'https://logo.clearbit.com/pg.com' },
  { symbol: 'DIS', name: 'Walt Disney Co.', type: 'stock', logoUrl: 'https://logo.clearbit.com/disney.com' },

  // Healthcare & Biotech
  { symbol: 'UNH', name: 'UnitedHealth Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/unitedhealthgroup.com' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', type: 'stock', logoUrl: 'https://logo.clearbit.com/jnj.com' },
  { symbol: 'LLY', name: 'Eli Lilly and Co.', type: 'stock', logoUrl: 'https://logo.clearbit.com/lilly.com' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/abbvie.com' },
  { symbol: 'MRK', name: 'Merck & Co.', type: 'stock', logoUrl: 'https://logo.clearbit.com/merck.com' },
  { symbol: 'PFE', name: 'Pfizer Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/pfizer.com' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', type: 'stock', logoUrl: 'https://logo.clearbit.com/thermofisher.com' },
  { symbol: 'ABT', name: 'Abbott Laboratories', type: 'stock', logoUrl: 'https://logo.clearbit.com/abbott.com' },
  { symbol: 'DHR', name: 'Danaher Corp.', type: 'stock', logoUrl: 'https://logo.clearbit.com/danaher.com' },
  { symbol: 'NVO', name: 'Novo Nordisk', type: 'stock', logoUrl: 'https://logo.clearbit.com/novonordisk.com' },

  // Energy & Industrials
  { symbol: 'XOM', name: 'Exxon Mobil', type: 'stock', logoUrl: 'https://logo.clearbit.com/exxonmobil.com' },
  { symbol: 'CVX', name: 'Chevron Corp.', type: 'stock', logoUrl: 'https://logo.clearbit.com/chevron.com' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/caterpillar.com' },
  { symbol: 'BA', name: 'Boeing Company', type: 'stock', logoUrl: 'https://logo.clearbit.com/boeing.com' },
  { symbol: 'GE', name: 'General Electric', type: 'stock', logoUrl: 'https://logo.clearbit.com/ge.com' },
  { symbol: 'UNP', name: 'Union Pacific', type: 'stock', logoUrl: 'https://logo.clearbit.com/up.com' },
  { symbol: 'UPS', name: 'United Parcel Service', type: 'stock', logoUrl: 'https://logo.clearbit.com/ups.com' },
  { symbol: 'HON', name: 'Honeywell', type: 'stock', logoUrl: 'https://logo.clearbit.com/honeywell.com' },
  { symbol: 'LMT', name: 'Lockheed Martin', type: 'stock', logoUrl: 'https://logo.clearbit.com/lockheedmartin.com' },
  { symbol: 'RTX', name: 'Raytheon Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/rtx.com' },

  // Telecommunications & Media
  { symbol: 'VZ', name: 'Verizon Communications', type: 'stock', logoUrl: 'https://logo.clearbit.com/verizon.com' },
  { symbol: 'T', name: 'AT&T Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/att.com' },
  { symbol: 'TMUS', name: 'T-Mobile US', type: 'stock', logoUrl: 'https://logo.clearbit.com/t-mobile.com' },
  { symbol: 'CMCSA', name: 'Comcast Corp.', type: 'stock', logoUrl: 'https://logo.clearbit.com/comcast.com' },
  { symbol: 'CHTR', name: 'Charter Communications', type: 'stock', logoUrl: 'https://logo.clearbit.com/spectrum.com' },

  // More High-Growth Tech / SaaS / Palantir etc.
  { symbol: 'PLTR', name: 'Palantir Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/palantir.com' },
  { symbol: 'SNOW', name: 'Snowflake Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/snowflake.com' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings', type: 'stock', logoUrl: 'https://logo.clearbit.com/crowdstrike.com' },
  { symbol: 'PANW', name: 'Palo Alto Networks', type: 'stock', logoUrl: 'https://logo.clearbit.com/paloaltonetworks.com' },
  { symbol: 'DDOG', name: 'Datadog Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/datadoghq.com' },
  { symbol: 'UBER', name: 'Uber Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/uber.com' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/airbnb.com' },
  { symbol: 'DASH', name: 'DoorDash Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/doordash.com' },
  { symbol: 'SHOP', name: 'Shopify Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/shopify.com' },
  { symbol: 'SPOT', name: 'Spotify Technology', type: 'stock', logoUrl: 'https://logo.clearbit.com/spotify.com' },
  { symbol: 'ROKU', name: 'Roku Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/roku.com' },
  { symbol: 'ZM', name: 'Zoom Video', type: 'stock', logoUrl: 'https://logo.clearbit.com/zoom.us' },
  { symbol: 'COIN', name: 'Coinbase Global', type: 'stock', logoUrl: 'https://logo.clearbit.com/coinbase.com' },

  // Top Cryptocurrencies
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png' },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png' },
  { id: 'tether', symbol: 'USDT', name: 'Tether', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/tether-usdt-logo.png' },
  { id: 'binancecoin', symbol: 'BNB', name: 'BNB', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/bnb-bnb-logo.png' },
  { id: 'solana', symbol: 'SOL', name: 'Solana', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/solana-sol-logo.png' },
  { id: 'ripple', symbol: 'XRP', name: 'XRP', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/xrp-xrp-logo.png' },
  { id: 'usd-coin', symbol: 'USDC', name: 'USDC', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png' },
  { id: 'cardano', symbol: 'ADA', name: 'Cardano', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/cardano-ada-logo.png' },
  { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/avalanche-avax-logo.png' },
  { id: 'dogecoin', symbol: 'DOGE', name: 'Dogecoin', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png' },
  { id: 'polkadot', symbol: 'DOT', name: 'Polkadot', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png' },
  { id: 'tron', symbol: 'TRX', name: 'TRON', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/tron-trx-logo.png' },
  { id: 'chainlink', symbol: 'LINK', name: 'Chainlink', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/chainlink-link-logo.png' },
  { id: 'matic-network', symbol: 'MATIC', name: 'Polygon', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/polygon-matic-logo.png' },
  { id: 'shiba-inu', symbol: 'SHIB', name: 'Shiba Inu', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png' },
  { id: 'litecoin', symbol: 'LTC', name: 'Litecoin', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/litecoin-ltc-logo.png' },
  { id: 'bitcoin-cash', symbol: 'BCH', name: 'Bitcoin Cash', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png' },
  { id: 'uniswap', symbol: 'UNI', name: 'Uniswap', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/uniswap-uni-logo.png' },
  { id: 'cosmos', symbol: 'ATOM', name: 'Cosmos', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/cosmos-atom-logo.png' },
  { id: 'stellar', symbol: 'XLM', name: 'Stellar', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/stellar-xlm-logo.png' },
  { id: 'monero', symbol: 'XMR', name: 'Monero', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/monero-xmr-logo.png' },
  { id: 'ethereum-classic', symbol: 'ETC', name: 'Ethereum Classic', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/ethereum-classic-etc-logo.png' },
  { id: 'filecoin', symbol: 'FIL', name: 'Filecoin', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/filecoin-fil-logo.png' },
  { id: 'internet-computer', symbol: 'ICP', name: 'Internet Computer', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/internet-computer-icp-logo.png' },
  { id: 'lido-dao', symbol: 'LDO', name: 'Lido DAO', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png' },
  { id: 'aptos', symbol: 'APT', name: 'Aptos', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/aptos-apt-logo.png' },
  { id: 'near', symbol: 'NEAR', name: 'NEAR Protocol', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/near-protocol-near-logo.png' },
  { id: 'vechain', symbol: 'VET', name: 'VeChain', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/vechain-vet-logo.png' },
  { id: 'maker', symbol: 'MKR', name: 'Maker', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/maker-mkr-logo.png' },
  { id: 'optimism', symbol: 'OP', name: 'Optimism', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.png' },
  { id: 'arbitrum', symbol: 'ARB', name: 'Arbitrum', type: 'crypto', logoUrl: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png' },

  // Top Index Funds & ETFs
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF', type: 'etf' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust (Nasdaq 100)', type: 'etf' },
  { symbol: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF', type: 'etf' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', type: 'etf' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', type: 'etf' },
  { symbol: 'IVV', name: 'iShares Core S&P 500 ETF', type: 'etf' },
  { symbol: 'SCHD', name: 'Schwab US Dividend Equity ETF', type: 'etf' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', type: 'etf' },
  { symbol: 'VIG', name: 'Vanguard Dividend Appreciation ETF', type: 'etf' },
  { symbol: 'VYM', name: 'Vanguard High Dividend Yield ETF', type: 'etf' },
  { symbol: 'VEA', name: 'Vanguard FTSE Developed Markets ETF', type: 'etf' },
  { symbol: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF', type: 'etf' },
  { symbol: 'VNQ', name: 'Vanguard Real Estate Index Fund', type: 'etf' },
  { symbol: 'BND', name: 'Vanguard Total Bond Market ETF', type: 'etf' },
  { symbol: 'GLD', name: 'SPDR Gold Shares', type: 'etf' },
  { symbol: 'SLV', name: 'iShares Silver Trust', type: 'etf' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF', type: 'etf' },
  { symbol: 'MMM', name: '3M', type: 'stock', logoUrl: 'https://logo.clearbit.com/mmm.com' },
  { symbol: 'AOS', name: 'A. O. Smith', type: 'stock', logoUrl: 'https://logo.clearbit.com/aos.com' },
  { symbol: 'ABMD', name: 'Abiomed', type: 'stock', logoUrl: 'https://logo.clearbit.com/abmd.com' },
  { symbol: 'ACN', name: 'Accenture', type: 'stock', logoUrl: 'https://logo.clearbit.com/acn.com' },
  { symbol: 'ATVI', name: 'Activision Blizzard', type: 'stock', logoUrl: 'https://logo.clearbit.com/atvi.com' },
  { symbol: 'ADM', name: 'ADM', type: 'stock', logoUrl: 'https://logo.clearbit.com/adm.com' },
  { symbol: 'AAP', name: 'Advance Auto Parts', type: 'stock', logoUrl: 'https://logo.clearbit.com/aap.com' },
  { symbol: 'AES', name: 'AES Corp', type: 'stock', logoUrl: 'https://logo.clearbit.com/aes.com' },
  { symbol: 'AFL', name: 'Aflac', type: 'stock', logoUrl: 'https://logo.clearbit.com/afl.com' },
  { symbol: 'A', name: 'Agilent Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/a.com' },
  { symbol: 'APD', name: 'Air Products & Chemicals', type: 'stock', logoUrl: 'https://logo.clearbit.com/apd.com' },
  { symbol: 'AKAM', name: 'Akamai Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/akam.com' },
  { symbol: 'ALK', name: 'Alaska Air Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/alk.com' },
  { symbol: 'ALB', name: 'Albemarle Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/alb.com' },
  { symbol: 'ARE', name: 'Alexandria Real Estate Equities', type: 'stock', logoUrl: 'https://logo.clearbit.com/are.com' },
  { symbol: 'ALGN', name: 'Align Technology', type: 'stock', logoUrl: 'https://logo.clearbit.com/algn.com' },
  { symbol: 'ALLE', name: 'Allegion', type: 'stock', logoUrl: 'https://logo.clearbit.com/alle.com' },
  { symbol: 'LNT', name: 'Alliant Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/lnt.com' },
  { symbol: 'ALL', name: 'Allstate Corp', type: 'stock', logoUrl: 'https://logo.clearbit.com/all.com' },
  { symbol: 'GOOG', name: 'Alphabet (Class C)', type: 'stock', logoUrl: 'https://logo.clearbit.com/goog.com' },
  { symbol: 'MO', name: 'Altria Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/mo.com' },
  { symbol: 'AMCR', name: 'Amcor', type: 'stock', logoUrl: 'https://logo.clearbit.com/amcr.com' },
  { symbol: 'AEE', name: 'Ameren Corp', type: 'stock', logoUrl: 'https://logo.clearbit.com/aee.com' },
  { symbol: 'AAL', name: 'American Airlines Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/aal.com' },
  { symbol: 'AEP', name: 'American Electric Power', type: 'stock', logoUrl: 'https://logo.clearbit.com/aep.com' },
  { symbol: 'AIG', name: 'American International Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/aig.com' },
  { symbol: 'AMT', name: 'American Tower', type: 'stock', logoUrl: 'https://logo.clearbit.com/amt.com' },
  { symbol: 'AWK', name: 'American Water Works', type: 'stock', logoUrl: 'https://logo.clearbit.com/awk.com' },
  { symbol: 'AMP', name: 'Ameriprise Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/amp.com' },
  { symbol: 'ABC', name: 'AmerisourceBergen', type: 'stock', logoUrl: 'https://logo.clearbit.com/abc.com' },
  { symbol: 'AME', name: 'Ametek', type: 'stock', logoUrl: 'https://logo.clearbit.com/ame.com' },
  { symbol: 'AMGN', name: 'Amgen', type: 'stock', logoUrl: 'https://logo.clearbit.com/amgn.com' },
  { symbol: 'APH', name: 'Amphenol', type: 'stock', logoUrl: 'https://logo.clearbit.com/aph.com' },
  { symbol: 'ADI', name: 'Analog Devices', type: 'stock', logoUrl: 'https://logo.clearbit.com/adi.com' },
  { symbol: 'ANSS', name: 'Ansys', type: 'stock', logoUrl: 'https://logo.clearbit.com/anss.com' },
  { symbol: 'ANTM', name: 'Anthem', type: 'stock', logoUrl: 'https://logo.clearbit.com/antm.com' },
  { symbol: 'AON', name: 'Aon', type: 'stock', logoUrl: 'https://logo.clearbit.com/aon.com' },
  { symbol: 'APA', name: 'APA Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/apa.com' },
  { symbol: 'AMAT', name: 'Applied Materials', type: 'stock', logoUrl: 'https://logo.clearbit.com/amat.com' },
  { symbol: 'APTV', name: 'Aptiv', type: 'stock', logoUrl: 'https://logo.clearbit.com/aptv.com' },
  { symbol: 'ANET', name: 'Arista Networks', type: 'stock', logoUrl: 'https://logo.clearbit.com/anet.com' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher & Co.', type: 'stock', logoUrl: 'https://logo.clearbit.com/ajg.com' },
  { symbol: 'AIZ', name: 'Assurant', type: 'stock', logoUrl: 'https://logo.clearbit.com/aiz.com' },
  { symbol: 'ATO', name: 'Atmos Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/ato.com' },
  { symbol: 'ADSK', name: 'Autodesk', type: 'stock', logoUrl: 'https://logo.clearbit.com/adsk.com' },
  { symbol: 'ADP', name: 'Automatic Data Processing', type: 'stock', logoUrl: 'https://logo.clearbit.com/adp.com' },
  { symbol: 'AZO', name: 'AutoZone', type: 'stock', logoUrl: 'https://logo.clearbit.com/azo.com' },
  { symbol: 'AVB', name: 'AvalonBay Communities', type: 'stock', logoUrl: 'https://logo.clearbit.com/avb.com' },
  { symbol: 'AVY', name: 'Avery Dennison', type: 'stock', logoUrl: 'https://logo.clearbit.com/avy.com' },
  { symbol: 'BKR', name: 'Baker Hughes', type: 'stock', logoUrl: 'https://logo.clearbit.com/bkr.com' },
  { symbol: 'BLL', name: 'Ball Corp', type: 'stock', logoUrl: 'https://logo.clearbit.com/bll.com' },
  { symbol: 'BBWI', name: 'Bath & Body Works Inc.', type: 'stock', logoUrl: 'https://logo.clearbit.com/bbwi.com' },
  { symbol: 'BAX', name: 'Baxter International', type: 'stock', logoUrl: 'https://logo.clearbit.com/bax.com' },
  { symbol: 'BDX', name: 'Becton Dickinson', type: 'stock', logoUrl: 'https://logo.clearbit.com/bdx.com' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway', type: 'stock', logoUrl: 'https://logo.clearbit.com/brk-b.com' },
  { symbol: 'BBY', name: 'Best Buy', type: 'stock', logoUrl: 'https://logo.clearbit.com/bby.com' },
  { symbol: 'BIO', name: 'Bio-Rad Laboratories', type: 'stock', logoUrl: 'https://logo.clearbit.com/bio.com' },
  { symbol: 'TECH', name: 'Bio-Techne', type: 'stock', logoUrl: 'https://logo.clearbit.com/tech.com' },
  { symbol: 'BIIB', name: 'Biogen', type: 'stock', logoUrl: 'https://logo.clearbit.com/biib.com' },
  { symbol: 'BK', name: 'BNY Mellon', type: 'stock', logoUrl: 'https://logo.clearbit.com/bk.com' },
  { symbol: 'BKNG', name: 'Booking Holdings', type: 'stock', logoUrl: 'https://logo.clearbit.com/bkng.com' },
  { symbol: 'BWA', name: 'BorgWarner', type: 'stock', logoUrl: 'https://logo.clearbit.com/bwa.com' },
  { symbol: 'BXP', name: 'Boston Properties', type: 'stock', logoUrl: 'https://logo.clearbit.com/bxp.com' },
  { symbol: 'BSX', name: 'Boston Scientific', type: 'stock', logoUrl: 'https://logo.clearbit.com/bsx.com' },
  { symbol: 'BMY', name: 'Bristol Myers Squibb', type: 'stock', logoUrl: 'https://logo.clearbit.com/bmy.com' },
  { symbol: 'BR', name: 'Broadridge Financial Solutions', type: 'stock', logoUrl: 'https://logo.clearbit.com/br.com' },
  { symbol: 'BRO', name: 'Brown & Brown', type: 'stock', logoUrl: 'https://logo.clearbit.com/bro.com' },
  { symbol: 'BF-B', name: 'Brown–Forman', type: 'stock', logoUrl: 'https://logo.clearbit.com/bf-b.com' },
  { symbol: 'CHRW', name: 'C. H. Robinson', type: 'stock', logoUrl: 'https://logo.clearbit.com/chrw.com' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', type: 'stock', logoUrl: 'https://logo.clearbit.com/cdns.com' },
  { symbol: 'CZR', name: 'Caesars Entertainment', type: 'stock', logoUrl: 'https://logo.clearbit.com/czr.com' },
  { symbol: 'CPB', name: 'Campbell Soup', type: 'stock', logoUrl: 'https://logo.clearbit.com/cpb.com' },
  { symbol: 'COF', name: 'Capital One Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/cof.com' },
  { symbol: 'CAH', name: 'Cardinal Health', type: 'stock', logoUrl: 'https://logo.clearbit.com/cah.com' },
  { symbol: 'KMX', name: 'CarMax', type: 'stock', logoUrl: 'https://logo.clearbit.com/kmx.com' },
  { symbol: 'CCL', name: 'Carnival Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/ccl.com' },
  { symbol: 'CARR', name: 'Carrier Global', type: 'stock', logoUrl: 'https://logo.clearbit.com/carr.com' },
  { symbol: 'CTLT', name: 'Catalent', type: 'stock', logoUrl: 'https://logo.clearbit.com/ctlt.com' },
  { symbol: 'CBOE', name: 'Cboe Global Markets', type: 'stock', logoUrl: 'https://logo.clearbit.com/cboe.com' },
  { symbol: 'CBRE', name: 'CBRE', type: 'stock', logoUrl: 'https://logo.clearbit.com/cbre.com' },
  { symbol: 'CDW', name: 'CDW', type: 'stock', logoUrl: 'https://logo.clearbit.com/cdw.com' },
  { symbol: 'CE', name: 'Celanese', type: 'stock', logoUrl: 'https://logo.clearbit.com/ce.com' },
  { symbol: 'CNC', name: 'Centene Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/cnc.com' },
  { symbol: 'CNP', name: 'CenterPoint Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/cnp.com' },
  { symbol: 'CDAY', name: 'Ceridian', type: 'stock', logoUrl: 'https://logo.clearbit.com/cday.com' },
  { symbol: 'CERN', name: 'Cerner', type: 'stock', logoUrl: 'https://logo.clearbit.com/cern.com' },
  { symbol: 'CF', name: 'CF Industries', type: 'stock', logoUrl: 'https://logo.clearbit.com/cf.com' },
  { symbol: 'CRL', name: 'Charles River Laboratories', type: 'stock', logoUrl: 'https://logo.clearbit.com/crl.com' },
  { symbol: 'SCHW', name: 'Charles Schwab Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/schw.com' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill', type: 'stock', logoUrl: 'https://logo.clearbit.com/cmg.com' },
  { symbol: 'CB', name: 'Chubb', type: 'stock', logoUrl: 'https://logo.clearbit.com/cb.com' },
  { symbol: 'CHD', name: 'Church & Dwight', type: 'stock', logoUrl: 'https://logo.clearbit.com/chd.com' },
  { symbol: 'CI', name: 'Cigna', type: 'stock', logoUrl: 'https://logo.clearbit.com/ci.com' },
  { symbol: 'CINF', name: 'Cincinnati Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/cinf.com' },
  { symbol: 'CTAS', name: 'Cintas Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/ctas.com' },
  { symbol: 'CFG', name: 'Citizens Financial Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/cfg.com' },
  { symbol: 'CTXS', name: 'Citrix Systems', type: 'stock', logoUrl: 'https://logo.clearbit.com/ctxs.com' },
  { symbol: 'CLX', name: 'Clorox', type: 'stock', logoUrl: 'https://logo.clearbit.com/clx.com' },
  { symbol: 'CME', name: 'CME Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/cme.com' },
  { symbol: 'CMS', name: 'CMS Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/cms.com' },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions', type: 'stock', logoUrl: 'https://logo.clearbit.com/ctsh.com' },
  { symbol: 'CL', name: 'Colgate-Palmolive', type: 'stock', logoUrl: 'https://logo.clearbit.com/cl.com' },
  { symbol: 'CMA', name: 'Comerica', type: 'stock', logoUrl: 'https://logo.clearbit.com/cma.com' },
  { symbol: 'CAG', name: 'Conagra Brands', type: 'stock', logoUrl: 'https://logo.clearbit.com/cag.com' },
  { symbol: 'COP', name: 'ConocoPhillips', type: 'stock', logoUrl: 'https://logo.clearbit.com/cop.com' },
  { symbol: 'ED', name: 'Consolidated Edison', type: 'stock', logoUrl: 'https://logo.clearbit.com/ed.com' },
  { symbol: 'STZ', name: 'Constellation Brands', type: 'stock', logoUrl: 'https://logo.clearbit.com/stz.com' },
  { symbol: 'CPRT', name: 'Copart', type: 'stock', logoUrl: 'https://logo.clearbit.com/cprt.com' },
  { symbol: 'GLW', name: 'Corning', type: 'stock', logoUrl: 'https://logo.clearbit.com/glw.com' },
  { symbol: 'CTVA', name: 'Corteva', type: 'stock', logoUrl: 'https://logo.clearbit.com/ctva.com' },
  { symbol: 'CTRA', name: 'Coterra', type: 'stock', logoUrl: 'https://logo.clearbit.com/ctra.com' },
  { symbol: 'CCI', name: 'Crown Castle', type: 'stock', logoUrl: 'https://logo.clearbit.com/cci.com' },
  { symbol: 'CSX', name: 'CSX', type: 'stock', logoUrl: 'https://logo.clearbit.com/csx.com' },
  { symbol: 'CMI', name: 'Cummins', type: 'stock', logoUrl: 'https://logo.clearbit.com/cmi.com' },
  { symbol: 'CVS', name: 'CVS Health', type: 'stock', logoUrl: 'https://logo.clearbit.com/cvs.com' },
  { symbol: 'DHI', name: 'D. R. Horton', type: 'stock', logoUrl: 'https://logo.clearbit.com/dhi.com' },
  { symbol: 'DRI', name: 'Darden Restaurants', type: 'stock', logoUrl: 'https://logo.clearbit.com/dri.com' },
  { symbol: 'DVA', name: 'DaVita', type: 'stock', logoUrl: 'https://logo.clearbit.com/dva.com' },
  { symbol: 'DE', name: 'Deere & Co.', type: 'stock', logoUrl: 'https://logo.clearbit.com/de.com' },
  { symbol: 'DAL', name: 'Delta Air Lines', type: 'stock', logoUrl: 'https://logo.clearbit.com/dal.com' },
  { symbol: 'XRAY', name: 'Dentsply Sirona', type: 'stock', logoUrl: 'https://logo.clearbit.com/xray.com' },
  { symbol: 'DVN', name: 'Devon Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/dvn.com' },
  { symbol: 'DXCM', name: 'DexCom', type: 'stock', logoUrl: 'https://logo.clearbit.com/dxcm.com' },
  { symbol: 'FANG', name: 'Diamondback Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/fang.com' },
  { symbol: 'DLR', name: 'Digital Realty Trust', type: 'stock', logoUrl: 'https://logo.clearbit.com/dlr.com' },
  { symbol: 'DFS', name: 'Discover Financial Services', type: 'stock', logoUrl: 'https://logo.clearbit.com/dfs.com' },
  { symbol: 'DISCA', name: 'Discovery (Series A)', type: 'stock', logoUrl: 'https://logo.clearbit.com/disca.com' },
  { symbol: 'DISCK', name: 'Discovery (Series C)', type: 'stock', logoUrl: 'https://logo.clearbit.com/disck.com' },
  { symbol: 'DISH', name: 'Dish Network', type: 'stock', logoUrl: 'https://logo.clearbit.com/dish.com' },
  { symbol: 'DG', name: 'Dollar General', type: 'stock', logoUrl: 'https://logo.clearbit.com/dg.com' },
  { symbol: 'DLTR', name: 'Dollar Tree', type: 'stock', logoUrl: 'https://logo.clearbit.com/dltr.com' },
  { symbol: 'D', name: 'Dominion Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/d.com' },
  { symbol: 'DPZ', name: 'Dominos Pizza', type: 'stock', logoUrl: 'https://logo.clearbit.com/dpz.com' },
  { symbol: 'DOV', name: 'Dover Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/dov.com' },
  { symbol: 'DOW', name: 'Dow', type: 'stock', logoUrl: 'https://logo.clearbit.com/dow.com' },
  { symbol: 'DTE', name: 'DTE Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/dte.com' },
  { symbol: 'DUK', name: 'Duke Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/duk.com' },
  { symbol: 'DRE', name: 'Duke Realty Corp', type: 'stock', logoUrl: 'https://logo.clearbit.com/dre.com' },
  { symbol: 'DD', name: 'DuPont', type: 'stock', logoUrl: 'https://logo.clearbit.com/dd.com' },
  { symbol: 'DXC', name: 'DXC Technology', type: 'stock', logoUrl: 'https://logo.clearbit.com/dxc.com' },
  { symbol: 'EMN', name: 'Eastman Chemical', type: 'stock', logoUrl: 'https://logo.clearbit.com/emn.com' },
  { symbol: 'ETN', name: 'Eaton Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/etn.com' },
  { symbol: 'EBAY', name: 'eBay', type: 'stock', logoUrl: 'https://logo.clearbit.com/ebay.com' },
  { symbol: 'ECL', name: 'Ecolab', type: 'stock', logoUrl: 'https://logo.clearbit.com/ecl.com' },
  { symbol: 'EIX', name: 'Edison International', type: 'stock', logoUrl: 'https://logo.clearbit.com/eix.com' },
  { symbol: 'EW', name: 'Edwards Lifesciences', type: 'stock', logoUrl: 'https://logo.clearbit.com/ew.com' },
  { symbol: 'EA', name: 'Electronic Arts', type: 'stock', logoUrl: 'https://logo.clearbit.com/ea.com' },
  { symbol: 'EMR', name: 'Emerson Electric Company', type: 'stock', logoUrl: 'https://logo.clearbit.com/emr.com' },
  { symbol: 'ENPH', name: 'Enphase Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/enph.com' },
  { symbol: 'ETR', name: 'Entergy', type: 'stock', logoUrl: 'https://logo.clearbit.com/etr.com' },
  { symbol: 'EOG', name: 'EOG Resources', type: 'stock', logoUrl: 'https://logo.clearbit.com/eog.com' },
  { symbol: 'EFX', name: 'Equifax', type: 'stock', logoUrl: 'https://logo.clearbit.com/efx.com' },
  { symbol: 'EQIX', name: 'Equinix', type: 'stock', logoUrl: 'https://logo.clearbit.com/eqix.com' },
  { symbol: 'EQR', name: 'Equity Residential', type: 'stock', logoUrl: 'https://logo.clearbit.com/eqr.com' },
  { symbol: 'ESS', name: 'Essex Property Trust', type: 'stock', logoUrl: 'https://logo.clearbit.com/ess.com' },
  { symbol: 'EL', name: 'Estée Lauder Companies', type: 'stock', logoUrl: 'https://logo.clearbit.com/el.com' },
  { symbol: 'ETSY', name: 'Etsy', type: 'stock', logoUrl: 'https://logo.clearbit.com/etsy.com' },
  { symbol: 'RE', name: 'Everest Re', type: 'stock', logoUrl: 'https://logo.clearbit.com/re.com' },
  { symbol: 'EVRG', name: 'Evergy', type: 'stock', logoUrl: 'https://logo.clearbit.com/evrg.com' },
  { symbol: 'ES', name: 'Eversource Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/es.com' },
  { symbol: 'EXC', name: 'Exelon', type: 'stock', logoUrl: 'https://logo.clearbit.com/exc.com' },
  { symbol: 'EXPE', name: 'Expedia Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/expe.com' },
  { symbol: 'EXPD', name: 'Expeditors', type: 'stock', logoUrl: 'https://logo.clearbit.com/expd.com' },
  { symbol: 'EXR', name: 'Extra Space Storage', type: 'stock', logoUrl: 'https://logo.clearbit.com/exr.com' },
  { symbol: 'FFIV', name: 'F5 Networks', type: 'stock', logoUrl: 'https://logo.clearbit.com/ffiv.com' },
  { symbol: 'FB', name: 'Facebook', type: 'stock', logoUrl: 'https://logo.clearbit.com/fb.com' },
  { symbol: 'FAST', name: 'Fastenal', type: 'stock', logoUrl: 'https://logo.clearbit.com/fast.com' },
  { symbol: 'FRT', name: 'Federal Realty Investment Trust', type: 'stock', logoUrl: 'https://logo.clearbit.com/frt.com' },
  { symbol: 'FDX', name: 'FedEx', type: 'stock', logoUrl: 'https://logo.clearbit.com/fdx.com' },
  { symbol: 'FIS', name: 'Fidelity National Information Services', type: 'stock', logoUrl: 'https://logo.clearbit.com/fis.com' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', type: 'stock', logoUrl: 'https://logo.clearbit.com/fitb.com' },
  { symbol: 'FRC', name: 'First Republic Bank', type: 'stock', logoUrl: 'https://logo.clearbit.com/frc.com' },
  { symbol: 'FE', name: 'FirstEnergy', type: 'stock', logoUrl: 'https://logo.clearbit.com/fe.com' },
  { symbol: 'FISV', name: 'Fiserv', type: 'stock', logoUrl: 'https://logo.clearbit.com/fisv.com' },
  { symbol: 'FLT', name: 'Fleetcor', type: 'stock', logoUrl: 'https://logo.clearbit.com/flt.com' },
  { symbol: 'FMC', name: 'FMC Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/fmc.com' },
  { symbol: 'F', name: 'Ford', type: 'stock', logoUrl: 'https://logo.clearbit.com/f.com' },
  { symbol: 'FTNT', name: 'Fortinet', type: 'stock', logoUrl: 'https://logo.clearbit.com/ftnt.com' },
  { symbol: 'FTV', name: 'Fortive', type: 'stock', logoUrl: 'https://logo.clearbit.com/ftv.com' },
  { symbol: 'FBHS', name: 'Fortune Brands Home & Security', type: 'stock', logoUrl: 'https://logo.clearbit.com/fbhs.com' },
  { symbol: 'FOXA', name: 'Fox Corporation (Class A)', type: 'stock', logoUrl: 'https://logo.clearbit.com/foxa.com' },
  { symbol: 'FOX', name: 'Fox Corporation (Class B)', type: 'stock', logoUrl: 'https://logo.clearbit.com/fox.com' },
  { symbol: 'BEN', name: 'Franklin Resources', type: 'stock', logoUrl: 'https://logo.clearbit.com/ben.com' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', type: 'stock', logoUrl: 'https://logo.clearbit.com/fcx.com' },
  { symbol: 'GPS', name: 'Gap', type: 'stock', logoUrl: 'https://logo.clearbit.com/gps.com' },
  { symbol: 'GRMN', name: 'Garmin', type: 'stock', logoUrl: 'https://logo.clearbit.com/grmn.com' },
  { symbol: 'IT', name: 'Gartner', type: 'stock', logoUrl: 'https://logo.clearbit.com/it.com' },
  { symbol: 'GNRC', name: 'Generac Holdings', type: 'stock', logoUrl: 'https://logo.clearbit.com/gnrc.com' },
  { symbol: 'GD', name: 'General Dynamics', type: 'stock', logoUrl: 'https://logo.clearbit.com/gd.com' },
  { symbol: 'GIS', name: 'General Mills', type: 'stock', logoUrl: 'https://logo.clearbit.com/gis.com' },
  { symbol: 'GM', name: 'General Motors', type: 'stock', logoUrl: 'https://logo.clearbit.com/gm.com' },
  { symbol: 'GPC', name: 'Genuine Parts', type: 'stock', logoUrl: 'https://logo.clearbit.com/gpc.com' },
  { symbol: 'GILD', name: 'Gilead Sciences', type: 'stock', logoUrl: 'https://logo.clearbit.com/gild.com' },
  { symbol: 'GPN', name: 'Global Payments', type: 'stock', logoUrl: 'https://logo.clearbit.com/gpn.com' },
  { symbol: 'GL', name: 'Globe Life', type: 'stock', logoUrl: 'https://logo.clearbit.com/gl.com' },
  { symbol: 'HAL', name: 'Halliburton', type: 'stock', logoUrl: 'https://logo.clearbit.com/hal.com' },
  { symbol: 'HBI', name: 'Hanesbrands', type: 'stock', logoUrl: 'https://logo.clearbit.com/hbi.com' },
  { symbol: 'HAS', name: 'Hasbro', type: 'stock', logoUrl: 'https://logo.clearbit.com/has.com' },
  { symbol: 'HCA', name: 'HCA Healthcare', type: 'stock', logoUrl: 'https://logo.clearbit.com/hca.com' },
  { symbol: 'PEAK', name: 'Healthpeak Properties', type: 'stock', logoUrl: 'https://logo.clearbit.com/peak.com' },
  { symbol: 'HSIC', name: 'Henry Schein', type: 'stock', logoUrl: 'https://logo.clearbit.com/hsic.com' },
  { symbol: 'HES', name: 'Hess Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/hes.com' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', type: 'stock', logoUrl: 'https://logo.clearbit.com/hpe.com' },
  { symbol: 'HLT', name: 'Hilton Worldwide', type: 'stock', logoUrl: 'https://logo.clearbit.com/hlt.com' },
  { symbol: 'HOLX', name: 'Hologic', type: 'stock', logoUrl: 'https://logo.clearbit.com/holx.com' },
  { symbol: 'HRL', name: 'Hormel', type: 'stock', logoUrl: 'https://logo.clearbit.com/hrl.com' },
  { symbol: 'HST', name: 'Host Hotels & Resorts', type: 'stock', logoUrl: 'https://logo.clearbit.com/hst.com' },
  { symbol: 'HWM', name: 'Howmet Aerospace', type: 'stock', logoUrl: 'https://logo.clearbit.com/hwm.com' },
  { symbol: 'HPQ', name: 'HP', type: 'stock', logoUrl: 'https://logo.clearbit.com/hpq.com' },
  { symbol: 'HUM', name: 'Humana', type: 'stock', logoUrl: 'https://logo.clearbit.com/hum.com' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', type: 'stock', logoUrl: 'https://logo.clearbit.com/hban.com' },
  { symbol: 'HII', name: 'Huntington Ingalls Industries', type: 'stock', logoUrl: 'https://logo.clearbit.com/hii.com' },
  { symbol: 'IEX', name: 'IDEX Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/iex.com' },
  { symbol: 'IDXX', name: 'Idexx Laboratories', type: 'stock', logoUrl: 'https://logo.clearbit.com/idxx.com' },
  { symbol: 'INFO', name: 'IHS Markit', type: 'stock', logoUrl: 'https://logo.clearbit.com/info.com' },
  { symbol: 'ITW', name: 'Illinois Tool Works', type: 'stock', logoUrl: 'https://logo.clearbit.com/itw.com' },
  { symbol: 'ILMN', name: 'Illumina', type: 'stock', logoUrl: 'https://logo.clearbit.com/ilmn.com' },
  { symbol: 'INCY', name: 'Incyte', type: 'stock', logoUrl: 'https://logo.clearbit.com/incy.com' },
  { symbol: 'IR', name: 'Ingersoll Rand', type: 'stock', logoUrl: 'https://logo.clearbit.com/ir.com' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', type: 'stock', logoUrl: 'https://logo.clearbit.com/ice.com' },
  { symbol: 'IFF', name: 'International Flavors & Fragrances', type: 'stock', logoUrl: 'https://logo.clearbit.com/iff.com' },
  { symbol: 'IP', name: 'International Paper', type: 'stock', logoUrl: 'https://logo.clearbit.com/ip.com' },
  { symbol: 'IPG', name: 'Interpublic Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/ipg.com' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', type: 'stock', logoUrl: 'https://logo.clearbit.com/isrg.com' },
  { symbol: 'IVZ', name: 'Invesco', type: 'stock', logoUrl: 'https://logo.clearbit.com/ivz.com' },
  { symbol: 'IPGP', name: 'IPG Photonics', type: 'stock', logoUrl: 'https://logo.clearbit.com/ipgp.com' },
  { symbol: 'IQV', name: 'IQVIA', type: 'stock', logoUrl: 'https://logo.clearbit.com/iqv.com' },
  { symbol: 'IRM', name: 'Iron Mountain', type: 'stock', logoUrl: 'https://logo.clearbit.com/irm.com' },
  { symbol: 'JBHT', name: 'J. B. Hunt', type: 'stock', logoUrl: 'https://logo.clearbit.com/jbht.com' },
  { symbol: 'JKHY', name: 'Jack Henry & Associates', type: 'stock', logoUrl: 'https://logo.clearbit.com/jkhy.com' },
  { symbol: 'J', name: 'Jacobs Engineering Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/j.com' },
  { symbol: 'SJM', name: 'JM Smucker', type: 'stock', logoUrl: 'https://logo.clearbit.com/sjm.com' },
  { symbol: 'JCI', name: 'Johnson Controls', type: 'stock', logoUrl: 'https://logo.clearbit.com/jci.com' },
  { symbol: 'JNPR', name: 'Juniper Networks', type: 'stock', logoUrl: 'https://logo.clearbit.com/jnpr.com' },
  { symbol: 'KSU', name: 'Kansas City Southern', type: 'stock', logoUrl: 'https://logo.clearbit.com/ksu.com' },
  { symbol: 'K', name: 'Kelloggs', type: 'stock', logoUrl: 'https://logo.clearbit.com/k.com' },
  { symbol: 'KEY', name: 'KeyCorp', type: 'stock', logoUrl: 'https://logo.clearbit.com/key.com' },
  { symbol: 'KEYS', name: 'Keysight Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/keys.com' },
  { symbol: 'KMB', name: 'Kimberly-Clark', type: 'stock', logoUrl: 'https://logo.clearbit.com/kmb.com' },
  { symbol: 'KIM', name: 'Kimco Realty', type: 'stock', logoUrl: 'https://logo.clearbit.com/kim.com' },
  { symbol: 'KMI', name: 'Kinder Morgan', type: 'stock', logoUrl: 'https://logo.clearbit.com/kmi.com' },
  { symbol: 'KLAC', name: 'KLA Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/klac.com' },
  { symbol: 'KHC', name: 'Kraft Heinz', type: 'stock', logoUrl: 'https://logo.clearbit.com/khc.com' },
  { symbol: 'KR', name: 'Kroger', type: 'stock', logoUrl: 'https://logo.clearbit.com/kr.com' },
  { symbol: 'LHX', name: 'L3Harris Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/lhx.com' },
  { symbol: 'LH', name: 'LabCorp', type: 'stock', logoUrl: 'https://logo.clearbit.com/lh.com' },
  { symbol: 'LRCX', name: 'Lam Research', type: 'stock', logoUrl: 'https://logo.clearbit.com/lrcx.com' },
  { symbol: 'LW', name: 'Lamb Weston', type: 'stock', logoUrl: 'https://logo.clearbit.com/lw.com' },
  { symbol: 'LVS', name: 'Las Vegas Sands', type: 'stock', logoUrl: 'https://logo.clearbit.com/lvs.com' },
  { symbol: 'LEG', name: 'Leggett & Platt', type: 'stock', logoUrl: 'https://logo.clearbit.com/leg.com' },
  { symbol: 'LDOS', name: 'Leidos', type: 'stock', logoUrl: 'https://logo.clearbit.com/ldos.com' },
  { symbol: 'LEN', name: 'Lennar', type: 'stock', logoUrl: 'https://logo.clearbit.com/len.com' },
  { symbol: 'LNC', name: 'Lincoln National', type: 'stock', logoUrl: 'https://logo.clearbit.com/lnc.com' },
  { symbol: 'LIN', name: 'Linde', type: 'stock', logoUrl: 'https://logo.clearbit.com/lin.com' },
  { symbol: 'LYV', name: 'Live Nation Entertainment', type: 'stock', logoUrl: 'https://logo.clearbit.com/lyv.com' },
  { symbol: 'LKQ', name: 'LKQ Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/lkq.com' },
  { symbol: 'L', name: 'Loews Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/l.com' },
  { symbol: 'LUMN', name: 'Lumen Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/lumn.com' },
  { symbol: 'LYB', name: 'LyondellBasell', type: 'stock', logoUrl: 'https://logo.clearbit.com/lyb.com' },
  { symbol: 'MTB', name: 'M&T Bank', type: 'stock', logoUrl: 'https://logo.clearbit.com/mtb.com' },
  { symbol: 'MRO', name: 'Marathon Oil', type: 'stock', logoUrl: 'https://logo.clearbit.com/mro.com' },
  { symbol: 'MPC', name: 'Marathon Petroleum', type: 'stock', logoUrl: 'https://logo.clearbit.com/mpc.com' },
  { symbol: 'MKTX', name: 'MarketAxess', type: 'stock', logoUrl: 'https://logo.clearbit.com/mktx.com' },
  { symbol: 'MAR', name: 'Marriott International', type: 'stock', logoUrl: 'https://logo.clearbit.com/mar.com' },
  { symbol: 'MMC', name: 'Marsh & McLennan', type: 'stock', logoUrl: 'https://logo.clearbit.com/mmc.com' },
  { symbol: 'MLM', name: 'Martin Marietta Materials', type: 'stock', logoUrl: 'https://logo.clearbit.com/mlm.com' },
  { symbol: 'MAS', name: 'Masco', type: 'stock', logoUrl: 'https://logo.clearbit.com/mas.com' },
  { symbol: 'MTCH', name: 'Match Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/mtch.com' },
  { symbol: 'MKC', name: 'McCormick & Company', type: 'stock', logoUrl: 'https://logo.clearbit.com/mkc.com' },
  { symbol: 'MCK', name: 'McKesson Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/mck.com' },
  { symbol: 'MDT', name: 'Medtronic', type: 'stock', logoUrl: 'https://logo.clearbit.com/mdt.com' },
  { symbol: 'MET', name: 'MetLife', type: 'stock', logoUrl: 'https://logo.clearbit.com/met.com' },
  { symbol: 'MTD', name: 'Mettler Toledo', type: 'stock', logoUrl: 'https://logo.clearbit.com/mtd.com' },
  { symbol: 'MGM', name: 'MGM Resorts International', type: 'stock', logoUrl: 'https://logo.clearbit.com/mgm.com' },
  { symbol: 'MCHP', name: 'Microchip Technology', type: 'stock', logoUrl: 'https://logo.clearbit.com/mchp.com' },
  { symbol: 'MU', name: 'Micron Technology', type: 'stock', logoUrl: 'https://logo.clearbit.com/mu.com' },
  { symbol: 'MAA', name: 'Mid-America Apartments', type: 'stock', logoUrl: 'https://logo.clearbit.com/maa.com' },
  { symbol: 'MRNA', name: 'Moderna', type: 'stock', logoUrl: 'https://logo.clearbit.com/mrna.com' },
  { symbol: 'MHK', name: 'Mohawk Industries', type: 'stock', logoUrl: 'https://logo.clearbit.com/mhk.com' },
  { symbol: 'TAP', name: 'Molson Coors Beverage Company', type: 'stock', logoUrl: 'https://logo.clearbit.com/tap.com' },
  { symbol: 'MDLZ', name: 'Mondelez International', type: 'stock', logoUrl: 'https://logo.clearbit.com/mdlz.com' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems', type: 'stock', logoUrl: 'https://logo.clearbit.com/mpwr.com' },
  { symbol: 'MNST', name: 'Monster Beverage', type: 'stock', logoUrl: 'https://logo.clearbit.com/mnst.com' },
  { symbol: 'MCO', name: 'Moodys Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/mco.com' },
  { symbol: 'MSI', name: 'Motorola Solutions', type: 'stock', logoUrl: 'https://logo.clearbit.com/msi.com' },
  { symbol: 'MSCI', name: 'MSCI', type: 'stock', logoUrl: 'https://logo.clearbit.com/msci.com' },
  { symbol: 'NDAQ', name: 'Nasdaq', type: 'stock', logoUrl: 'https://logo.clearbit.com/ndaq.com' },
  { symbol: 'NTAP', name: 'NetApp', type: 'stock', logoUrl: 'https://logo.clearbit.com/ntap.com' },
  { symbol: 'NWL', name: 'Newell Brands', type: 'stock', logoUrl: 'https://logo.clearbit.com/nwl.com' },
  { symbol: 'NEM', name: 'Newmont', type: 'stock', logoUrl: 'https://logo.clearbit.com/nem.com' },
  { symbol: 'NWSA', name: 'News Corp (Class A)', type: 'stock', logoUrl: 'https://logo.clearbit.com/nwsa.com' },
  { symbol: 'NWS', name: 'News Corp (Class B)', type: 'stock', logoUrl: 'https://logo.clearbit.com/nws.com' },
  { symbol: 'NEE', name: 'NextEra Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/nee.com' },
  { symbol: 'NLSN', name: 'Nielsen Holdings', type: 'stock', logoUrl: 'https://logo.clearbit.com/nlsn.com' },
  { symbol: 'NI', name: 'NiSource', type: 'stock', logoUrl: 'https://logo.clearbit.com/ni.com' },
  { symbol: 'NSC', name: 'Norfolk Southern', type: 'stock', logoUrl: 'https://logo.clearbit.com/nsc.com' },
  { symbol: 'NTRS', name: 'Northern Trust', type: 'stock', logoUrl: 'https://logo.clearbit.com/ntrs.com' },
  { symbol: 'NOC', name: 'Northrop Grumman', type: 'stock', logoUrl: 'https://logo.clearbit.com/noc.com' },
  { symbol: 'NLOK', name: 'NortonLifeLock', type: 'stock', logoUrl: 'https://logo.clearbit.com/nlok.com' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line Holdings', type: 'stock', logoUrl: 'https://logo.clearbit.com/nclh.com' },
  { symbol: 'NRG', name: 'NRG Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/nrg.com' },
  { symbol: 'NUE', name: 'Nucor', type: 'stock', logoUrl: 'https://logo.clearbit.com/nue.com' },
  { symbol: 'NVR', name: 'NVR', type: 'stock', logoUrl: 'https://logo.clearbit.com/nvr.com' },
  { symbol: 'NXPI', name: 'NXP', type: 'stock', logoUrl: 'https://logo.clearbit.com/nxpi.com' },
  { symbol: 'ORLY', name: 'OReilly Automotive', type: 'stock', logoUrl: 'https://logo.clearbit.com/orly.com' },
  { symbol: 'OXY', name: 'Occidental Petroleum', type: 'stock', logoUrl: 'https://logo.clearbit.com/oxy.com' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line', type: 'stock', logoUrl: 'https://logo.clearbit.com/odfl.com' },
  { symbol: 'OMC', name: 'Omnicom Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/omc.com' },
  { symbol: 'OKE', name: 'Oneok', type: 'stock', logoUrl: 'https://logo.clearbit.com/oke.com' },
  { symbol: 'OGN', name: 'Organon & Co.', type: 'stock', logoUrl: 'https://logo.clearbit.com/ogn.com' },
  { symbol: 'OTIS', name: 'Otis Worldwide', type: 'stock', logoUrl: 'https://logo.clearbit.com/otis.com' },
  { symbol: 'PCAR', name: 'Paccar', type: 'stock', logoUrl: 'https://logo.clearbit.com/pcar.com' },
  { symbol: 'PKG', name: 'Packaging Corporation of America', type: 'stock', logoUrl: 'https://logo.clearbit.com/pkg.com' },
  { symbol: 'PH', name: 'Parker-Hannifin', type: 'stock', logoUrl: 'https://logo.clearbit.com/ph.com' },
  { symbol: 'PAYX', name: 'Paychex', type: 'stock', logoUrl: 'https://logo.clearbit.com/payx.com' },
  { symbol: 'PAYC', name: 'Paycom', type: 'stock', logoUrl: 'https://logo.clearbit.com/payc.com' },
  { symbol: 'PENN', name: 'Penn National Gaming', type: 'stock', logoUrl: 'https://logo.clearbit.com/penn.com' },
  { symbol: 'PNR', name: 'Pentair', type: 'stock', logoUrl: 'https://logo.clearbit.com/pnr.com' },
  { symbol: 'PBCT', name: 'Peoples United Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/pbct.com' },
  { symbol: 'PKI', name: 'PerkinElmer', type: 'stock', logoUrl: 'https://logo.clearbit.com/pki.com' },
  { symbol: 'PM', name: 'Philip Morris International', type: 'stock', logoUrl: 'https://logo.clearbit.com/pm.com' },
  { symbol: 'PSX', name: 'Phillips 66', type: 'stock', logoUrl: 'https://logo.clearbit.com/psx.com' },
  { symbol: 'PNW', name: 'Pinnacle West Capital', type: 'stock', logoUrl: 'https://logo.clearbit.com/pnw.com' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources', type: 'stock', logoUrl: 'https://logo.clearbit.com/pxd.com' },
  { symbol: 'PNC', name: 'PNC Financial Services', type: 'stock', logoUrl: 'https://logo.clearbit.com/pnc.com' },
  { symbol: 'POOL', name: 'Pool Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/pool.com' },
  { symbol: 'PPG', name: 'PPG Industries', type: 'stock', logoUrl: 'https://logo.clearbit.com/ppg.com' },
  { symbol: 'PPL', name: 'PPL', type: 'stock', logoUrl: 'https://logo.clearbit.com/ppl.com' },
  { symbol: 'PFG', name: 'Principal Financial Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/pfg.com' },
  { symbol: 'PGR', name: 'Progressive Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/pgr.com' },
  { symbol: 'PLD', name: 'Prologis', type: 'stock', logoUrl: 'https://logo.clearbit.com/pld.com' },
  { symbol: 'PRU', name: 'Prudential Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/pru.com' },
  { symbol: 'PTC', name: 'PTC', type: 'stock', logoUrl: 'https://logo.clearbit.com/ptc.com' },
  { symbol: 'PEG', name: 'Public Service Enterprise Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/peg.com' },
  { symbol: 'PSA', name: 'Public Storage', type: 'stock', logoUrl: 'https://logo.clearbit.com/psa.com' },
  { symbol: 'PHM', name: 'PulteGroup', type: 'stock', logoUrl: 'https://logo.clearbit.com/phm.com' },
  { symbol: 'PVH', name: 'PVH', type: 'stock', logoUrl: 'https://logo.clearbit.com/pvh.com' },
  { symbol: 'QRVO', name: 'Qorvo', type: 'stock', logoUrl: 'https://logo.clearbit.com/qrvo.com' },
  { symbol: 'PWR', name: 'Quanta Services', type: 'stock', logoUrl: 'https://logo.clearbit.com/pwr.com' },
  { symbol: 'DGX', name: 'Quest Diagnostics', type: 'stock', logoUrl: 'https://logo.clearbit.com/dgx.com' },
  { symbol: 'RL', name: 'Ralph Lauren Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/rl.com' },
  { symbol: 'RJF', name: 'Raymond James Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/rjf.com' },
  { symbol: 'O', name: 'Realty Income Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/o.com' },
  { symbol: 'REG', name: 'Regency Centers', type: 'stock', logoUrl: 'https://logo.clearbit.com/reg.com' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', type: 'stock', logoUrl: 'https://logo.clearbit.com/regn.com' },
  { symbol: 'RF', name: 'Regions Financial Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/rf.com' },
  { symbol: 'RSG', name: 'Republic Services', type: 'stock', logoUrl: 'https://logo.clearbit.com/rsg.com' },
  { symbol: 'RMD', name: 'ResMed', type: 'stock', logoUrl: 'https://logo.clearbit.com/rmd.com' },
  { symbol: 'RHI', name: 'Robert Half International', type: 'stock', logoUrl: 'https://logo.clearbit.com/rhi.com' },
  { symbol: 'ROK', name: 'Rockwell Automation', type: 'stock', logoUrl: 'https://logo.clearbit.com/rok.com' },
  { symbol: 'ROL', name: 'Rollins', type: 'stock', logoUrl: 'https://logo.clearbit.com/rol.com' },
  { symbol: 'ROP', name: 'Roper Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/rop.com' },
  { symbol: 'ROST', name: 'Ross Stores', type: 'stock', logoUrl: 'https://logo.clearbit.com/rost.com' },
  { symbol: 'RCL', name: 'Royal Caribbean Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/rcl.com' },
  { symbol: 'SPGI', name: 'S&P Global', type: 'stock', logoUrl: 'https://logo.clearbit.com/spgi.com' },
  { symbol: 'SBAC', name: 'SBA Communications', type: 'stock', logoUrl: 'https://logo.clearbit.com/sbac.com' },
  { symbol: 'SLB', name: 'Schlumberger', type: 'stock', logoUrl: 'https://logo.clearbit.com/slb.com' },
  { symbol: 'STX', name: 'Seagate Technology', type: 'stock', logoUrl: 'https://logo.clearbit.com/stx.com' },
  { symbol: 'SEE', name: 'Sealed Air', type: 'stock', logoUrl: 'https://logo.clearbit.com/see.com' },
  { symbol: 'SRE', name: 'Sempra Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/sre.com' },
  { symbol: 'SHW', name: 'Sherwin-Williams', type: 'stock', logoUrl: 'https://logo.clearbit.com/shw.com' },
  { symbol: 'SPG', name: 'Simon Property Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/spg.com' },
  { symbol: 'SWKS', name: 'Skyworks Solutions', type: 'stock', logoUrl: 'https://logo.clearbit.com/swks.com' },
  { symbol: 'SNA', name: 'Snap-on', type: 'stock', logoUrl: 'https://logo.clearbit.com/sna.com' },
  { symbol: 'SO', name: 'Southern Company', type: 'stock', logoUrl: 'https://logo.clearbit.com/so.com' },
  { symbol: 'LUV', name: 'Southwest Airlines', type: 'stock', logoUrl: 'https://logo.clearbit.com/luv.com' },
  { symbol: 'SWK', name: 'Stanley Black & Decker', type: 'stock', logoUrl: 'https://logo.clearbit.com/swk.com' },
  { symbol: 'STT', name: 'State Street Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/stt.com' },
  { symbol: 'STE', name: 'Steris', type: 'stock', logoUrl: 'https://logo.clearbit.com/ste.com' },
  { symbol: 'SYK', name: 'Stryker Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/syk.com' },
  { symbol: 'SIVB', name: 'SVB Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/sivb.com' },
  { symbol: 'SYF', name: 'Synchrony Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/syf.com' },
  { symbol: 'SNPS', name: 'Synopsys', type: 'stock', logoUrl: 'https://logo.clearbit.com/snps.com' },
  { symbol: 'SYY', name: 'Sysco', type: 'stock', logoUrl: 'https://logo.clearbit.com/syy.com' },
  { symbol: 'TROW', name: 'T. Rowe Price', type: 'stock', logoUrl: 'https://logo.clearbit.com/trow.com' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', type: 'stock', logoUrl: 'https://logo.clearbit.com/ttwo.com' },
  { symbol: 'TPR', name: 'Tapestry', type: 'stock', logoUrl: 'https://logo.clearbit.com/tpr.com' },
  { symbol: 'TEL', name: 'TE Connectivity', type: 'stock', logoUrl: 'https://logo.clearbit.com/tel.com' },
  { symbol: 'TDY', name: 'Teledyne Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/tdy.com' },
  { symbol: 'TFX', name: 'Teleflex', type: 'stock', logoUrl: 'https://logo.clearbit.com/tfx.com' },
  { symbol: 'TER', name: 'Teradyne', type: 'stock', logoUrl: 'https://logo.clearbit.com/ter.com' },
  { symbol: 'TXT', name: 'Textron', type: 'stock', logoUrl: 'https://logo.clearbit.com/txt.com' },
  { symbol: 'COO', name: 'The Cooper Companies', type: 'stock', logoUrl: 'https://logo.clearbit.com/coo.com' },
  { symbol: 'HIG', name: 'The Hartford', type: 'stock', logoUrl: 'https://logo.clearbit.com/hig.com' },
  { symbol: 'HSY', name: 'The Hershey Company', type: 'stock', logoUrl: 'https://logo.clearbit.com/hsy.com' },
  { symbol: 'MOS', name: 'The Mosaic Company', type: 'stock', logoUrl: 'https://logo.clearbit.com/mos.com' },
  { symbol: 'TRV', name: 'The Travelers Companies', type: 'stock', logoUrl: 'https://logo.clearbit.com/trv.com' },
  { symbol: 'TJX', name: 'TJX Companies', type: 'stock', logoUrl: 'https://logo.clearbit.com/tjx.com' },
  { symbol: 'TSCO', name: 'Tractor Supply Company', type: 'stock', logoUrl: 'https://logo.clearbit.com/tsco.com' },
  { symbol: 'TT', name: 'Trane Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/tt.com' },
  { symbol: 'TDG', name: 'TransDigm Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/tdg.com' },
  { symbol: 'TRMB', name: 'Trimble', type: 'stock', logoUrl: 'https://logo.clearbit.com/trmb.com' },
  { symbol: 'TFC', name: 'Truist Financial', type: 'stock', logoUrl: 'https://logo.clearbit.com/tfc.com' },
  { symbol: 'TWTR', name: 'Twitter', type: 'stock', logoUrl: 'https://logo.clearbit.com/twtr.com' },
  { symbol: 'TYL', name: 'Tyler Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/tyl.com' },
  { symbol: 'TSN', name: 'Tyson Foods', type: 'stock', logoUrl: 'https://logo.clearbit.com/tsn.com' },
  { symbol: 'USB', name: 'U.S. Bancorp', type: 'stock', logoUrl: 'https://logo.clearbit.com/usb.com' },
  { symbol: 'UDR', name: 'UDR', type: 'stock', logoUrl: 'https://logo.clearbit.com/udr.com' },
  { symbol: 'ULTA', name: 'Ulta Beauty', type: 'stock', logoUrl: 'https://logo.clearbit.com/ulta.com' },
  { symbol: 'UAA', name: 'Under Armour (Class A)', type: 'stock', logoUrl: 'https://logo.clearbit.com/uaa.com' },
  { symbol: 'UA', name: 'Under Armour (Class C)', type: 'stock', logoUrl: 'https://logo.clearbit.com/ua.com' },
  { symbol: 'UAL', name: 'United Airlines', type: 'stock', logoUrl: 'https://logo.clearbit.com/ual.com' },
  { symbol: 'URI', name: 'United Rentals', type: 'stock', logoUrl: 'https://logo.clearbit.com/uri.com' },
  { symbol: 'UHS', name: 'Universal Health Services', type: 'stock', logoUrl: 'https://logo.clearbit.com/uhs.com' },
  { symbol: 'VLO', name: 'Valero Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/vlo.com' },
  { symbol: 'VTR', name: 'Ventas', type: 'stock', logoUrl: 'https://logo.clearbit.com/vtr.com' },
  { symbol: 'VRSN', name: 'Verisign', type: 'stock', logoUrl: 'https://logo.clearbit.com/vrsn.com' },
  { symbol: 'VRSK', name: 'Verisk Analytics', type: 'stock', logoUrl: 'https://logo.clearbit.com/vrsk.com' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', type: 'stock', logoUrl: 'https://logo.clearbit.com/vrtx.com' },
  { symbol: 'VFC', name: 'VF Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/vfc.com' },
  { symbol: 'VIAC', name: 'ViacomCBS', type: 'stock', logoUrl: 'https://logo.clearbit.com/viac.com' },
  { symbol: 'VTRS', name: 'Viatris', type: 'stock', logoUrl: 'https://logo.clearbit.com/vtrs.com' },
  { symbol: 'VNO', name: 'Vornado Realty Trust', type: 'stock', logoUrl: 'https://logo.clearbit.com/vno.com' },
  { symbol: 'VMC', name: 'Vulcan Materials', type: 'stock', logoUrl: 'https://logo.clearbit.com/vmc.com' },
  { symbol: 'WRB', name: 'W. R. Berkley Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/wrb.com' },
  { symbol: 'GWW', name: 'W. W. Grainger', type: 'stock', logoUrl: 'https://logo.clearbit.com/gww.com' },
  { symbol: 'WAB', name: 'Wabtec', type: 'stock', logoUrl: 'https://logo.clearbit.com/wab.com' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance', type: 'stock', logoUrl: 'https://logo.clearbit.com/wba.com' },
  { symbol: 'WM', name: 'Waste Management', type: 'stock', logoUrl: 'https://logo.clearbit.com/wm.com' },
  { symbol: 'WAT', name: 'Waters Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/wat.com' },
  { symbol: 'WEC', name: 'WEC Energy Group', type: 'stock', logoUrl: 'https://logo.clearbit.com/wec.com' },
  { symbol: 'WELL', name: 'Welltower', type: 'stock', logoUrl: 'https://logo.clearbit.com/well.com' },
  { symbol: 'WST', name: 'West Pharmaceutical Services', type: 'stock', logoUrl: 'https://logo.clearbit.com/wst.com' },
  { symbol: 'WDC', name: 'Western Digital', type: 'stock', logoUrl: 'https://logo.clearbit.com/wdc.com' },
  { symbol: 'WU', name: 'Western Union', type: 'stock', logoUrl: 'https://logo.clearbit.com/wu.com' },
  { symbol: 'WRK', name: 'WestRock', type: 'stock', logoUrl: 'https://logo.clearbit.com/wrk.com' },
  { symbol: 'WY', name: 'Weyerhaeuser', type: 'stock', logoUrl: 'https://logo.clearbit.com/wy.com' },
  { symbol: 'WHR', name: 'Whirlpool Corporation', type: 'stock', logoUrl: 'https://logo.clearbit.com/whr.com' },
  { symbol: 'WMB', name: 'Williams Companies', type: 'stock', logoUrl: 'https://logo.clearbit.com/wmb.com' },
  { symbol: 'WLTW', name: 'Willis Towers Watson', type: 'stock', logoUrl: 'https://logo.clearbit.com/wltw.com' },
  { symbol: 'WYNN', name: 'Wynn Resorts', type: 'stock', logoUrl: 'https://logo.clearbit.com/wynn.com' },
  { symbol: 'XEL', name: 'Xcel Energy', type: 'stock', logoUrl: 'https://logo.clearbit.com/xel.com' },
  { symbol: 'XLNX', name: 'Xilinx', type: 'stock', logoUrl: 'https://logo.clearbit.com/xlnx.com' },
  { symbol: 'XYL', name: 'Xylem', type: 'stock', logoUrl: 'https://logo.clearbit.com/xyl.com' },
  { symbol: 'YUM', name: 'Yum! Brands', type: 'stock', logoUrl: 'https://logo.clearbit.com/yum.com' },
  { symbol: 'ZBRA', name: 'Zebra Technologies', type: 'stock', logoUrl: 'https://logo.clearbit.com/zbra.com' },
  { symbol: 'ZBH', name: 'Zimmer Biomet', type: 'stock', logoUrl: 'https://logo.clearbit.com/zbh.com' },
  { symbol: 'ZION', name: 'Zions Bancorp', type: 'stock', logoUrl: 'https://logo.clearbit.com/zion.com' },
  { symbol: 'ZTS', name: 'Zoetis', type: 'stock', logoUrl: 'https://logo.clearbit.com/zts.com' },
];
